### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by UKenGB** [JacquesTur/Ninext#2]
Does the code to load these have to be run for every session or only once and persistent between sessions?

What is meant by 'file' and 'comment' in badges.html:? To what are you referring since Ninox is a database and as such, one is not working with either?

In the Ninox editor, I already see a list of possible 'completions'. What does completion.html do that Ninox is not already doing?

The above are not criticisms in any way, just confusion on my part.

**Comment by JacquesTur** [comment]
Dear Ken,

1 - The code must be loaded at each session, every time you open a database.

2 - Queue and How corresponds to the 2 trombone system icon and message bubble that are at the top right of the forms. These are the files and comments that can be attached to a record.
<img width="80" alt="image" src="https://user-images.githubusercontent.com/80148405/182624710-3d668dbe-279e-4471-8cb0-2c25e17acd4b.png">. Badges allow you to visually know if there is information attached to the current registration.

3 - Completion.html only sets the Ninox code editor that natively embeds this feature. 2 months after I did this, Ninox included it in its code better and with a possibility to search/replace in the editor. So now, Completion.html is no longer useful. However, it remains compatible with the Ninox competition.

To disable it, simply set the completion parameter to false 
```
var configLoadModules := {
        completion: false,
        badges: true,
        ...
    };
```

4 - No problem, all remarks, and even criticism, are welcome. With it we can progress. Thank's for your message🙏

**Comment by JacquesTur** [comment]
> Does the code to load these have to be run for every session or only once and persistent between sessions?
> 
> What is meant by 'file' and 'comment' in badges.html:? To what are you referring since Ninox is a database and as such, one is not working with either?
> 
> In the Ninox editor, I already see a list of possible 'completions'. What does completion.html do that Ninox is not already doing?
> 
> The above are not criticisms in any way, just confusion on my part.

**Comment by UKenGB** [comment]
Thanks Jaques, Badges could be useful, but I suspected that Ninox introduced completion in the editor after you created this extra functions, so will set it off (false).

Could the code to load your functions be run from a Database's 'Trigger after open'? Seems that would be the obvious place or is there a reason why not?

**Comment by JacquesTur** [comment]
> Could the code to load your functions be run from a Database's 'Trigger after open'? Seems that would be the obvious place or is there a reason why not?

Yes, it is best to open an initialization window from the 'Trigger after open' trigger. I'm sending you an example application via the forum.
